test: This is nothing

test2:
  test22: this is something

esminipath: "F:\\myProjects\\av\\esmini"
rootPath: "F:\\myProjects\\av\\junction-art"

default_lane_width: 3
default_max_lane_width: 4

max_left_turn_angle: 120
min_right_turn_angle: 240

random_max_lanes: 2
random_max_median_turns: 2
random_max_edge_turns: 2
random_max_merge_lanes: 2
random_max_min_angle_between_roads: 30
random_max_max_angle_between_roads: 120

harvested_straight_roads: "./output/harvest-straight-US.dill"