package:
  name: junction-art
  version: "0.1"

source:
  git_rev: 
  git_url: https://github.com/adhocmaster/junction-art.git 

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - dill
    - pyyaml

test:
  imports: 
   - examples
   - extensions
   - junctions
   - library
   - pyodrx

about:
  home: https://github.com/adhocmaster/junction-art.git